name: R-CMD-check

on:
  - push
  # - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # - name: Notify slack success
      #   if: success()
      #   id: slack # IMPORTANT: reference this step ID value in future Slack steps
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel_id: C023D5FGS5U
      #     status: STARTING
      #     color: warning

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1
        with:
          args: '"--no-manual", "--no-build-vignettes"'

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      # - name: Notify slack success
      #   if: success()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     # Updates existing message from the first step
      #     message_id: ${{ steps.slack.outputs.message_id }}
      #     channel_id: C023D5FGS5U
      #     status: SUCCESS
      #     color: good

      # - name: Notify slack fail
      #   if: failure()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     # Updates existing message from the first step
      #     message_id: ${{ steps.slack.outputs.message_id }}
      #     channel_id: C023D5FGS5U
      #     status: FAILED
      #     color: danger

